### PR TITLE
Flask monitoring with flask_monitoringdashboard

### PR DESCRIPTION
**Pull request by CaroCardozo**

### CODE REVIEW

**Review by RFX14 — COMMENTED** [review]
Just curious why'd you remove the version number for Flask, and Jinja2

**Review by RFX14 — CHANGES_REQUESTED** [review]
I would put the flask and jinja versions back on, unless you really need them to not be there anymore

**Comment by CaroCardozo** [comment]
@RFX14 Because the flask monitoring tool use different version of jinja that Flask use so Flask needed to use past versions. When you delete the versions "pip" manage the versions for you and as it appears, it did not change the project funtionality

**Review by RFX14 — APPROVED** [review]
lgtm!!

**Pull request merged**
